# Домашняя работа-5 (к лекции от 10.12.2018)

In [2]:
import numpy as np
import pandas as pd

# Задание-1
'''Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).'''

In [3]:
np_arr_1 = np.arange( 9, -1, -1 )

In [4]:
np_arr_1

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

# Задание-2
'''Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.'''

In [5]:
n = 10
np_diag_1 = np.diag( np.arange(n), k=0 ) 

In [6]:
np_diag_1

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [7]:
sum_diag_1 = np_diag_1.sum()
sum_diag_1

45

In [8]:
sum_diag_2 = sum( [ np_diag_1[i][j] for i in range(n) for j in range(n) if i == j ] )
sum_diag_2

45

# Задание-3
'''Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. 
Определите какому фильму было выставлено больше всего оценок 5.0.'''

In [9]:
df_ratings = pd.read_csv('ml-latest-small/ratings.csv')
df_ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [10]:
len(df_ratings)

100836

In [11]:
df_ratings_filtred = df_ratings[ df_ratings['rating'] == 5.0]
df_ratings_filtred.head()

userId  movieId  rating  timestamp
3       1       47     5.0  964983815
4       1       50     5.0  964982931
6       1      101     5.0  964980868
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [12]:
len(df_ratings_filtred)

13211

In [13]:
movieId_max, *_ = df_ratings_filtred['movieId'].value_counts().head(1)
print("Код фильма к наибольшим кол-во оценок 5.0 -", movieId_max)

Код фильма к наибольшим кол-во оценок 5.0 - 153


# Задание-4
'''По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) 
категорий 4, 12 и 21 за период с 2005 по 2010 года. 
Не учитывайте в расчетах отрицательные значения quantity.'''

In [14]:
df_power = pd.read_csv('power.csv')
df_power.head()

country  year  quantity  category
0  Austria  1996       5.0         1
1  Austria  1995      17.0         1
2  Belgium  2014       0.0         1
3  Belgium  2013       0.0         1
4  Belgium  2012      35.0         1

In [15]:
df_power.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1189482 entries, 0 to 1189481
Data columns (total 4 columns):
country     1189482 non-null object
year        1189482 non-null int64
quantity    1189482 non-null float64
category    1189482 non-null int64
dtypes: float64(1), int64(2), object(1)
memory usage: 36.3+ MB


In [16]:
len(df_power)

1189482

In [29]:
df_power_filtred = df_power[ ( 
                                df_power['country'].isin(['Estonia', 'Lithuania', 'Latvia'])
                             ) & (
                                    df_power['category'].isin([4, 12, 21]) 
                                ) & (
                                        (df_power['year'] >= 2005) &
                                        (df_power['year'] <= 2010)
    
                                    ) & (df_power['quantity'] >= 0)
                            ]
df_power_filtred.head()

country  year  quantity  category
10617    Estonia  2008       1.0         4
10618    Estonia  2007       0.0         4
10619    Estonia  2006       0.0         4
10620    Estonia  2005       1.0         4
11156  Lithuania  2008       1.0         4

In [30]:
len(df_power_filtred)

408

In [31]:
print("Cуммарное потребление - ", df_power_filtred['quantity'].sum())

Cуммарное потребление -  240580.0


# Задание-5
'''Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3'''

In [32]:
# Коэффициенты при переменных в левой части
coeff = np.array( [[4, 2, 1],
                  [1, 3, 0],
                  [0, 5, 4]] )

In [33]:
# Вектор свободных членов
vector = np.array( [4, 12, -3] )

In [34]:
from numpy import linalg

In [35]:
linalg.solve( coeff, vector )

array([ 0.46666667,  3.84444444, -5.55555556])

In [36]:
# Проверка
check = np.dot( coeff, linalg.solve( coeff, vector ) )
check

array([ 4., 12., -3.])

In [37]:
np.allclose(check, vector)

True